### ISSUE TITLE
Any document of it?

### ISSUE THREAD

**Issue by willard-yuan** [ovilab/elegant-hdf5#1]
@dragly Hi dragly, the elegant-hdf5 is really elegant when writing data to file. I'm trying to use it to save   data, but I face problem when starting using it. Would you like you provide some installation to use it?

**Comment by dragly** [comment]
Hi @willard-yuan. This package is currently in an early testing stage. Please be aware that the API may change drastically in the time ahead. Also, be careful with using it with important data. Side-effects may occur. Note also that i haven't had the time to work on elegant-hdf5 for some time now. I do however hope to add some improvements soon. Please feel free to share your experience with it and add issues if you encounter any bugs.

I have added some instructions on how you can install and test it to the [README.md](README.md) file. That should hopefully let you try it out for yourself. Note that it currently depends on qmake to be built. In the future I'm looking to change the build system to something more common, like cmake.
